#!/usr/bin/env python
import modules.messages as msg
import modules.defaults as defaults
import modules.GBM as gbm
import modules.BAT as bat
import modules.distance as dist
import modules.luminosity as lumi
import modules.visualize as visual
import modules.reference as ref
import modules.helpers as hlp

msg.banner()

my_data = defaults.my_data()
while True:
    choice = msg.mainmenu()
    if choice in ('q', 'Q'):
        break
    elif choice == '1':
        gbm.read(my_data) 
    elif choice == '2':
        bat.read(my_data)
    elif choice == '3':
        visual.init(my_data)
    elif choice == '4':
        lumi.select_proxy(my_data)
    elif choice == '5':
        dist.init(my_data)
    elif choice == '6':
        ref.read(my_data)
    elif choice in ('I', 'i'):
        my_data = hlp.importjson()
    elif choice in ('E', 'e'):
        hlp.exportjson(my_data)
    else:
       msg.menu_err() 

print(my_data)
